version: "3.3"
services:
  api:
    container_name: my-email-api-container
    restart: always
    #build: .
    build:
      context: .
      dockerfile: Dockerfile.jvm
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  postgres:
    container_name: my-email-api-db-container
    image: postgres:latest
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: mysecretpassword